version: '2.1'
services:
  backend:
    image: useless-ktor:latest
    mem_limit: 1024m
    restart: always
    ports:
      - "8081:8080"
  prometheus:
    image: prom/prometheus
    links:
      - backend
    ports:
      - "8082:9090"
    volumes:
      - ./monitoring:/etc/prometheus/
  grafana:
    image: grafana/grafana
    user: "104"
    links:
      - backend
      - prometheus
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    ports:
      - "8083:3000"
